version: '3'
services:
  email-service:
    image: dxh30/mail-svc:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    # Add other environment variables as needed
